labels:
  - name: "PROJECT EPIC"
    description: "Epic"
    color: "#d73a4a"

  - name: "type: bug"
    color: "#CC0000"
    description: An issue with the system ğŸ›.

  - name: "type: feature"
    color: "#009933"
    description: A feature request ğŸ“¦.

  - name: "type: testing"
    color: "#9933CC"
    description: An issue with the test suite ğŸ“¦.

  - name: "type: improvement"
    color: "#FFCC00"
    description: An improvement to the system ğŸ”¨.

  - name: "type: documentation"
    color: "#0000FF"
    description: A request for documentation ğŸ“–.

  - name: "type: question"
    color: "#0066CC"
    description: A question about the system ğŸ’¬.

  - name: "type: refactor"
    color: "#993399"
    description: A code change that neither fixes a bug nor adds a feature ğŸ”¨.

  - name: "type: other"
    color: "#000000"
    description: Other ğŸ¤·.

  - name: "priority: critical"
    color: "#CC0000"
    description: A critical issue ğŸ”¥.

  - name: "priority: high"
    color: "#FFCC00"
    description: A high priority issue ğŸ”¥.

  - name: "priority: medium"
    color: "#FFCC00"
    description: A medium priority issue ğŸ”¥.

  - name: "priority: low"
    color: "#009933"
    description: A low priority issue ğŸ”¥.

  - name: "priority: trivial"
    color: "#0066CC"
    description: A trivial issue ğŸ”¥.

  - name: "priority: other"
    color: "#000000"
    description: Other ğŸ¤·.

  - name: "status: open"
    color: "#0066CC"
    description: An open issue ğŸ”¥.

  - name: "status: closed"
    color: "#CC0000"
    description: A closed issue ğŸ”¥.

  - name: "status: merged"
    color: "#009933"
    description: A merged issue ğŸ”¥.

  - name: "status: other"
    color: "#000000"
    description: Other ğŸ¤·.

  - name: "status: duplicate"
    color: "#FFCC00"
    description: A duplicate issue ğŸ”¥.

  - name: "status: invalid"
    color: "#FFCC00"
    description: An invalid issue ğŸ”¥.

  - name: "status: wontfix"
    color: "#FFCC00"
    description: A wontfix issue ğŸ”¥.

  - name: "status: verified"
    color: "#009933"
    description: A verified issue ğŸ”¥.

  - name: "status: needs review"
    color: "#FFCC00"
    description: A needs review issue ğŸ”¥.

  - name: "status: needs discussion"
    color: "#FFCC00"
    description: A needs discussion issue ğŸ”¥.

  - name: "status: blcoked"
    color: "#FFCC00"
    description: A blocked issue ğŸ”¥.

  - name: "scope: ux"
    color: "#0066CC"
    description: A UX issue ğŸ”¥.

  - name: "scope: ui"
    color: "#0066CC"
    description: A User Interface issue ğŸ”¥.

  - name: "scope: security"
    color: "#0066CC"
    description: A security issue ğŸ”¥.

  - name: "scope: performance"
    color: "#0066CC"
    description: A performance issue ğŸ”¥.

  - name: "scope: other"
    color: "#000000"
    description: Other ğŸ¤·.

  - name: "scope: dx"
    color: "#0066CC"
    description: A Developer Experiece issue ğŸ”¥.

  - name: "scope: ci/cd"
    color: "#0066CC"
    description: A CI/CD issue ğŸ”¥.

  - name: "scope: seo"
    color: "#0066CC"
    description: A SEO issue ğŸ”¥.

  - name: "scope: accessibility"
    color: "#0066CC"
    description: An accessibility issue ğŸ”¥.
